[package]
name = "my-perseus-app"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perseus = { version = "0.3.6", features = [ "hydrate" ] }
serde = "1.0.152"
serde_json = "1.0.93"
sycamore = "0.7"
