// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/api/user/[id].ts";
import * as $2 from "./routes/api/user/create.ts";
import * as $3 from "./routes/api/user/login.ts";
import * as $4 from "./routes/api/user/logout.ts";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/sign-in.tsx";
import * as $7 from "./routes/sign-up.tsx";
import * as $$0 from "./islands/AuthForm.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/LinkButton.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/api/user/[id].ts": $1,
    "./routes/api/user/create.ts": $2,
    "./routes/api/user/login.ts": $3,
    "./routes/api/user/logout.ts": $4,
    "./routes/index.tsx": $5,
    "./routes/sign-in.tsx": $6,
    "./routes/sign-up.tsx": $7,
  },
  islands: {
    "./islands/AuthForm.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/LinkButton.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
